name: 🚀 Deploy to JagoanHosting

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      full_upload:
        description: "Force upload all files? (true/false)"
        required: false
        default: "false"

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📂 Checkout repository
        uses: actions/checkout@v3

      - name: 🧹 Remove FTP sync state if full upload
        if: ${{ github.event.inputs.full_upload == 'true' }}
        run: rm -f .ftp-deploy-sync-state.json

      - name: 📤 Deploy to JagoanHosting via FTP To ${{ secrets.FTP_HOST }}
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          protocol: ftp
          port: 21
